# Generated by Django 4.2.7 on 2023-11-29 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "bsk_app",
            "0007_remove_notification_is_read_remove_notification_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="path",
        ),
    ]
