# Generated by Django 4.2.7 on 2023-11-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsk_app", "0008_remove_notification_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="ProfileImage",
        ),
    ]
