# Generated by Django 4.2.7 on 2023-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsk_app", "0010_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="emoticon",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
