# Generated by Django 4.2.7 on 2023-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsk_app", "0011_notification_emoticon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
